name: Trigger Groundwire Build
on:
  push:
    branches:
      - gw/next/kelvin/408

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gwbtc/urbit build
        run: |
          gh workflow run groundwire-build.yml \
            --repo gwbtc/urbit \
            --ref gw/next/kelvin/408
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
